# DeepSeek API配置
api:
  # LLM提供者: "deepseek"或"openai"
  provider: "deepseek"
  # DeepSeek API密钥
  api_key: "sk-4deda1f0569f4e8486e6d19d1aea5412"
  # API基础URL
  base_url: "https://api.deepseek.com/v1"
  # 使用的模型
  model: "deepseek-chat"
  # 请求超时时间(秒)
  timeout: 120
# 安全设置
security:
  # 危险命令需要确认
  confirm_dangerous_commands: true
  # 完全禁止的命令列表
  blocked_commands:
    - "rm -rf / --no-preserve-root"
    - "mkfs"
    - "> /dev/sda"
    - ":(){:|:&};:"
  # 需要确认的命令模式
  confirm_patterns:
    - "rm\\s+-rf\\s+"
    - "dd\\s+if=.+\\s+of=/dev/"
    - "mkfs\\..+"
    - ";\\s*rm\\s"
    - ">\\s*/etc/"
    - ">\\s*/boot/"

# 用户界面设置
ui:
  # 是否启用彩色输出
  color_output: true
  # 历史记录文件
  history_file: "~/.linuxagent_history"
  # 最大历史记录条数
  max_history: 1000
  # 总是使用流式输出回答问题
  always_stream: true
  # 界面主题
  theme: "default"
  # 界面语言
  language: "zh"
  # 教程完成状态文件
  tutorial_state_file: "~/.linuxagent_tutorial_completed"

# 日志设置
logging:
  # 日志级别: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"
  # 日志文件路径
  file: "~/.linuxagent.log"
  # 日志轮换大小(MB)
  max_size_mb: 10
  # 保留的日志文件数量
  backup_count: 5

# 数据分析和推荐设置
analytics:
  # 启用命令推荐功能
  enable_recommendations: true
  # 收集使用数据进行分析
  collect_analytics: true
  # 显示详细统计信息
  detailed_stats: true
  # 启用性能基准测试
  enable_benchmarking: false 