"""Structured command plan models and parsing."""

from .file_patch import (
    FilePatchApplyError,
    FilePatchBackupRecord,
    FilePatchChangeSummary,
    FilePatchPermissionChange,
    FilePatchPlan,
    FilePatchPlanParseError,
    FilePatchSafetyReport,
    FilePatchTransactionResult,
    PatchApplyResult,
    apply_file_patch_plan,
    apply_unified_diff,
    evaluate_file_patch_plan,
    file_patch_plan_json,
    parse_file_patch_plan,
    select_file_patch_plan_files,
    summarize_file_patch_plan,
)
from .models import (
    CommandPlan,
    CommandPlanParseError,
    NoChangePlan,
    NoChangePlanParseError,
    PlannedCommand,
    command_plan_json,
    parse_command_plan,
    parse_no_change_plan,
)

__all__ = [
    "CommandPlan",
    "CommandPlanParseError",
    "FilePatchApplyError",
    "FilePatchBackupRecord",
    "FilePatchPermissionChange",
    "FilePatchPlan",
    "FilePatchPlanParseError",
    "FilePatchSafetyReport",
    "FilePatchTransactionResult",
    "FilePatchChangeSummary",
    "NoChangePlan",
    "NoChangePlanParseError",
    "PatchApplyResult",
    "PlannedCommand",
    "apply_file_patch_plan",
    "apply_unified_diff",
    "command_plan_json",
    "evaluate_file_patch_plan",
    "file_patch_plan_json",
    "parse_command_plan",
    "parse_file_patch_plan",
    "parse_no_change_plan",
    "select_file_patch_plan_files",
    "summarize_file_patch_plan",
]
