#!/usr/bin/env bash
# bootstrap.sh — initialize a LinuxAgent v4 source checkout.
# Creates a venv, installs dev extras, seeds the global user config, and
# installs a user-level launcher so `linuxagent` works outside the checkout.
#
# Usage:
#   ./scripts/bootstrap.sh           # default: ./.venv
#   VENV=myenv ./scripts/bootstrap.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PYTHON="${PYTHON:-python3}"
VENV="${VENV:-.venv}"
ORIGINAL_PATH="${PATH}"
CONFIG_DIR="${HOME}/.config/linuxagent"
CONFIG_PATH="${CONFIG_DIR}/config.yaml"
USER_BIN="${HOME}/.local/bin"
LAUNCHER_PATH="${USER_BIN}/linuxagent"
LAUNCHER_MARKER="Generated by LinuxAgent bootstrap"
ENV_MARKER_BEGIN="# >>> LinuxAgent bootstrap config >>>"
ENV_MARKER_END="# <<< LinuxAgent bootstrap config <<<"
SHELL_PROFILE="${LINUXAGENT_SHELL_PROFILE:-}"

shell_quote() {
    local value="$1"
    printf "'%s'" "${value//\'/\'\"\'\"\'}"
}

default_shell_profile() {
    if [[ -n "$SHELL_PROFILE" ]]; then
        printf '%s\n' "$SHELL_PROFILE"
        return
    fi
    case "${SHELL:-}" in
        */zsh) printf '%s\n' "${HOME}/.zshrc" ;;
        *) printf '%s\n' "${HOME}/.bashrc" ;;
    esac
}

install_config_env() {
    local profile_path="$1"
    local quoted_config
    local tmp_profile

    quoted_config="$(shell_quote "$CONFIG_PATH")"
    mkdir -p "$(dirname "$profile_path")"
    tmp_profile="${profile_path}.tmp.$$"
    if [[ -f "$profile_path" ]]; then
        awk -v begin="$ENV_MARKER_BEGIN" -v end="$ENV_MARKER_END" '
            $0 == begin { skip = 1; next }
            $0 == end { skip = 0; next }
            skip != 1 { print }
        ' "$profile_path" > "$tmp_profile"
    else
        : > "$tmp_profile"
    fi
    {
        printf '\n%s\n' "$ENV_MARKER_BEGIN"
        printf '%s\n' '# Generated by LinuxAgent bootstrap; path only, secrets stay in config.yaml.'
        printf 'export LINUXAGENT_CONFIG=%s\n' "$quoted_config"
        printf '%s\n' "$ENV_MARKER_END"
    } >> "$tmp_profile"
    mv "$tmp_profile" "$profile_path"
}

echo "==> Using ${PYTHON} -> $(${PYTHON} --version 2>&1)"
if [[ ! -d "$VENV" ]]; then
    echo "==> Creating virtualenv in ${VENV}"
    "$PYTHON" -m venv "$VENV"
fi
VENV_PATH="$(cd "$VENV" && pwd -P)"

# shellcheck source=/dev/null
source "${VENV_PATH}/bin/activate"

echo "==> Upgrading pip"
python -m pip install --upgrade pip

echo "==> Installing linuxagent (editable) with dev extras"
pip install -e ".[dev]"

echo "==> Preparing global config at ${CONFIG_PATH}"
mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"
if [[ ! -f "$CONFIG_PATH" ]]; then
    config_source="configs/example.yaml"
    if [[ -f "./config.yaml" ]]; then
        config_source="./config.yaml"
    fi
    cp "$config_source" "$CONFIG_PATH"
    chmod 600 "$CONFIG_PATH"
    echo "    Edit ${CONFIG_PATH} and set api.api_key before running live."
else
    current_mode=$(stat -c '%a' "$CONFIG_PATH" 2>/dev/null || stat -f '%Lp' "$CONFIG_PATH")
    if [[ "${current_mode}" != "600" ]]; then
        echo "==> ${CONFIG_PATH} mode is ${current_mode}; fixing to 600"
        chmod 600 "$CONFIG_PATH"
    fi
fi

if [[ -f "./config.yaml" ]]; then
    current_mode=$(stat -c '%a' ./config.yaml 2>/dev/null || stat -f '%Lp' ./config.yaml)
    if [[ "${current_mode}" != "600" ]]; then
        echo "==> ./config.yaml mode is ${current_mode}; fixing to 600"
        chmod 600 ./config.yaml
    fi
fi

profile_path="$(default_shell_profile)"
echo "==> Setting LINUXAGENT_CONFIG in ${profile_path}"
install_config_env "$profile_path"

echo "==> Installing user launcher at ${LAUNCHER_PATH}"
mkdir -p "$USER_BIN"
if [[ -e "$LAUNCHER_PATH" ]] && ! grep -q "$LAUNCHER_MARKER" "$LAUNCHER_PATH" 2>/dev/null; then
    echo "    ${LAUNCHER_PATH} already exists; leaving it unchanged."
    echo "    Use ${VENV_PATH}/bin/linuxagent directly, or remove the existing file and re-run bootstrap."
else
    tmp_launcher="${LAUNCHER_PATH}.tmp.$$"
    {
        printf '%s\n' '#!/usr/bin/env bash'
        printf '# %s; re-run scripts/bootstrap.sh after moving the checkout.\n' "$LAUNCHER_MARKER"
        printf 'if [[ -z "${LINUXAGENT_CONFIG:-}" ]]; then\n'
        printf '    export LINUXAGENT_CONFIG=%s\n' "$(shell_quote "$CONFIG_PATH")"
        printf 'fi\n'
        printf 'exec %q "$@"\n' "${VENV_PATH}/bin/linuxagent"
    } > "$tmp_launcher"
    chmod 755 "$tmp_launcher"
    mv "$tmp_launcher" "$LAUNCHER_PATH"
fi

case ":${ORIGINAL_PATH}:" in
    *":${USER_BIN}:"*) ;;
    *)
        echo "==> ${USER_BIN} is not on PATH."
        echo "    Add this to your shell profile: export PATH=\"${USER_BIN}:\$PATH\""
        ;;
esac

resolved_linuxagent="$(
    PATH="$ORIGINAL_PATH"
    command -v linuxagent 2>/dev/null || true
)"
if [[ -n "$resolved_linuxagent" && "$resolved_linuxagent" != "$LAUNCHER_PATH" ]]; then
    echo "==> Another linuxagent is earlier on PATH: ${resolved_linuxagent}"
    echo "    Put ${USER_BIN} before it on PATH to use this checkout globally."
fi

echo "==> Installing pre-commit hooks (best-effort)"
pre-commit install || echo "    pre-commit install skipped (not critical)"

cat <<'EOF'

Done. LinuxAgent is installed for this user.

Quick checks:
  source ~/.bashrc    # or open a new shell
  echo $LINUXAGENT_CONFIG
  command -v linuxagent
  linuxagent --help
  linuxagent check        # validate config loads
  make test
  make lint
EOF
